import = ["catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[window]
decorations = "none"
padding.x = 2
padding.y = 2
